# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9105a729bd5f88afb02ba21220677706c502ab83e9fc78850e0b9e919fd591b21088db7fca013dd2d752712af32464f47af9582ef59a7c6753eb81490e7e758

test:
  secret_key_base: 90573aba30aeb2dc5f8ab6d9cd1192c22f7bbf667bc8d11dd193c04b4dc84ef8c6f03ccf8faed676918521d744db419be1ce15c35a263b9c278875db790f3f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
